//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sgrc.DikizaCS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_Client()
        {
            this.db_Program = new HashSet<db_Program>();
            this.db_User = new HashSet<db_User>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string SecurityStampId { get; set; }
        public Nullable<bool> IsAccountConfirmed { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public string ContactName { get; set; }
        public string ContactSurname { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_Program> db_Program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_User> db_User { get; set; }
    }
}
