//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sgrc.DikizaCS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_LogBook
    {
        public long Id { get; set; }
        public long ProgramId { get; set; }
        public long UserId { get; set; }
        public Nullable<System.DateTime> WeekStartDate { get; set; }
        public Nullable<System.DateTime> WeekEndDate { get; set; }
        public decimal TimeHours { get; set; }
        public Nullable<decimal> TimeMinutes { get; set; }
        public Nullable<int> WeekNumber { get; set; }
        public string ActivityDescription { get; set; }
        public string ActivityType { get; set; }
        public Nullable<System.DateTime> DateOfActivity { get; set; }
        public string Remarks { get; set; }
        public bool IsSubmited { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
        public Nullable<System.DateTime> LastdateModified { get; set; }
        public Nullable<long> ModifiedByUser { get; set; }
        public System.DateTime CreationDateTime { get; set; }
    
        public virtual db_Program db_Program { get; set; }
        public virtual db_User db_User { get; set; }
    }
}
