//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sgrc.DikizaCS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_User()
        {
            this.db_LogBook = new HashSet<db_LogBook>();
            this.db_UserRole = new HashSet<db_UserRole>();
        }
    
        public long Id { get; set; }
        public Nullable<long> ClientId { get; set; }
        public Nullable<long> ProgramId { get; set; }
        public System.Guid SecurityStamp { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public string TelephoneNumber { get; set; }
        public string EmailConfirmationCode { get; set; }
        public Nullable<bool> IsEmailConfirmed { get; set; }
        public Nullable<System.DateTime> LastLoginDateTime { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreationDateTime { get; set; }
    
        public virtual db_Client db_Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_LogBook> db_LogBook { get; set; }
        public virtual db_Program db_Program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_UserRole> db_UserRole { get; set; }
    }
}
