//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sgrc.DikizaCS.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DikizaCSEntities : DbContext
    {
        public DikizaCSEntities()
            : base("name=DikizaCSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<db_Client> db_Client { get; set; }
        public virtual DbSet<db_LogBook> db_LogBook { get; set; }
        public virtual DbSet<db_Program> db_Program { get; set; }
        public virtual DbSet<db_Role> db_Role { get; set; }
        public virtual DbSet<db_User> db_User { get; set; }
        public virtual DbSet<db_UserRole> db_UserRole { get; set; }
    }
}
